import re

with open('src/App.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

target = r"                          \{/\* Top Individuals By Category \*/\}\n                          \{topStudentsByCategory\.some\(c => c\.students\.length > 0\) && \(\n                            <div className=\"bg-stone-900 border border-amber-500/20 rounded-2xl p-6\">\n                              <h3 className=\"text-lg font-black text-amber-300 mb-6 flex items-center gap-2\">\n                                <Layers className=\"w-5 h-5 text-amber-50\" />\n                                Top Individuals By Category\n                              </h3>\n                              <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\">\n                                \{topStudentsByCategory\.map\(\(catData\) => \(\n                                  <div key=\{catData\.category\} className=\"bg-stone-950 p-4 rounded-xl border border-stone-800 flex flex-col\">\n                                    <div className=\"flex items-center justify-between mb-3 border-b border-stone-800 pb-2\">\n                                      <h4 className=\"font-black text-amber-100\">\{catData\.category\}</h4>\n                                      <span className=\"text-\[10px\] text-amber-500/60 font-bold bg-amber-500/10 px-2 py-0\.5 rounded-full\">\{catData\.malayalam\}</span>\n                                    </div>\n                                    <div className=\"space-y-2 flex-1\">\n                                      \{catData\.students\.map\(\(student, idx\) => \(\n                                        <div key=\{student\.code\} className=\"flex items-center justify-between\">\n                                          <div className=\"flex items-center gap-2\">\n                                            <span className=\{\`w-4 text-center text-\[10px\] font-black \$\{idx === 0 \? 'text-amber-50' : 'text-stone-600'\}\`\}>\{idx \+ 1\}</span>\n                                            <div>\n                                              <div className=\{\`text-sm font-bold leading-tight \$\{idx === 0 \? 'text-stone-400' : 'text-stone-400'\}\`\}>\{student\.name\}</div>\n                                              <div className=\"text-\[9px\] text-stone-500\">\{student\.team\}</div>\n                                            </div>\n                                          </div>\n                                          <span className=\{\`text-sm font-black \$\{idx === 0 \? 'text-amber-400' : 'text-stone-500'\}\`\}>\{student\.points\}</span>\n                                        </div>\n                                      \)\)\}\n                                    </div>\n                                  </div>\n                                \)\)\}\n                              </div>\n                            </div>\n                          \)\}"

content = re.sub(target, "", content)

with open('src/App.tsx', 'w', encoding='utf-8') as f:
    f.write(content)

print("Removed Top Individuals By Category from Admin Dashboard")
